export const metadata = {
    title: 'Auth Pages',
    description: 'Generated by Next.js',
  }
  
  export default function RootLayout({
    children,
  }: {
    children: React.ReactNode
  }) {
    return (
      <>
        <h3>Authentication Routes</h3>
        <div>{children}</div>
        </>
    )
  }
